Fix rpm build when man pages are compressed with zstd (#447)
Some distros compress man pages with zstd instead of gzip, so the build
produces *.zst files while %files still lists *.gz:

  error: File not found: .../usr/share/man/man8/rshim.8.gz

Use a wildcard for the man page extension in both spec files.

RM #5332815
Orig-RM: #5300098

Signed-off-by: Daniel Belaish <dbelaish@nvidia.com>

(cherry picked from commit c8446b3aa4b1466d903fc896ceaa67b54849abbc)